# setup-all.yml
---
- name: Master Setup
  hosts: k8s_master
  become: yes
  vars_files:
    - vars/main.yml
  roles:
    - common
  tasks:
    - import_tasks: playbooks/master-setup.yml

- name: Worker Setup
  hosts: k8s_worker
  become: yes
  vars_files:
    - vars/main.yml
  tasks:
    - import_tasks: playbooks/worker-setup.yml

- name: Outline Setup
  hosts: outline_host
  become: yes
  vars_files:
    - vars/main.yml
  tasks:
    - import_tasks: playbooks/outline-setup.yml

- name: VPN API Setup
  hosts: vpn_api
  become: yes
  vars_files:
    - vars/main.yml
  tasks:
    - import_tasks: playbooks/vpn-api-setup.yml
