---
- name: Обновление репозиториев apt
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Установка основных пакетов
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - software-properties-common
      - python3-pip
      - python3-setuptools
      - ntp
      - ntpdate
      - iptables
      - iptables-persistent
    state: present

- name: Отключение swap
  command: swapoff -a
  changed_when: false

- name: Удаление swap из /etc/fstab
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'

- name: Обновление времени
  command: ntpdate time.nist.gov
  ignore_errors: yes

- name: Включить переадресацию IPv4
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    reload: yes

- name: Установка iptables правил
  template:
    src: iptables.j2
    dest: /etc/iptables/rules.v4
  notify:
    - Применить правила iptables

- name: Обновить apt и установить пакеты необходимые для Docker
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: present
    update_cache: yes

- name: Добавить GPG ключ Docker
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Добавить репозиторий Docker
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present

- name: Установить Docker
  apt:
    name:
      - docker-ce={{ docker_version }}
      - docker-ce-cli={{ docker_version }}
      - containerd.io
    state: present
    update_cache: yes

- name: Добавить GPG ключ Kubernetes
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Добавить репозиторий Kubernetes
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: kubernetes

- name: Установить kubeadm, kubelet и kubectl
  apt:
    name:
      - kubelet={{ kubernetes_version }}-00
      - kubeadm={{ kubernetes_version }}-00
      - kubectl={{ kubernetes_version }}-00
    state: present
    update_cache: yes

- name: Зафиксировать версию Kubernetes пакетов
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - kubelet
    - kubeadm
    - kubectl
    - docker-ce
    - docker-ce-cli