---
- name: Обновление репозиториев apt
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Установка основных пакетов
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - software-properties-common
      - python3-pip
      - python3-setuptools
      - ntp
      - ntpdate
      - iptables
      - iptables-persistent
    state: present

- name: Отключение swap
  command: swapoff -a
  changed_when: false

- name: Удаление swap из /etc/fstab
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'

- name: Обновление времени
  command: ntpdate time.nist.gov
  ignore_errors: yes

- name: Включить переадресацию IPv4
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    reload: yes

- name: Установка iptables правил
  template:
    src: iptables.j2
    dest: /etc/iptables/rules.v4
  notify:
    - Применить правила iptables

#- name: Обновить apt и установить пакеты необходимые для Docker
#  apt:
#    name:
#      - apt-transport-https
#      - ca-certificates
#      - curl
#      - gnupg-agent
#      - software-properties-common
#    state: present
#    update_cache: yes
#
#- name: Создать директорию для ключей Docker
#  file:
#    path: /etc/apt/keyrings
#    state: directory
#    mode: 0755
#
#- name: Скачать GPG ключ Docker
#  get_url:
#    url: https://download.docker.com/linux/ubuntu/gpg
#    dest: /tmp/docker.key
#    mode: 0644
#
#- name: Добавить ключ Docker в новый формат
#  shell: |
#    cat /tmp/docker.key | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
#    chmod a+r /etc/apt/keyrings/docker.gpg
#
#- name: Добавить репозиторий Docker
#  apt_repository:
#    repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
#    state: present
#    filename: docker

- name: Создать директорию для ключей Kubernetes
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: 0755

- name: Скачать и установить GPG ключ Kubernetes (новый способ)
  shell: |
    curl -fsSL https://pkgs.k8s.io/kubernetes-apt-keyring.gpg | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    chmod a+r /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  args:
    creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg


- name: Добавить репозиторий Kubernetes
  apt_repository:
    repo: deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/k8s.io/apt/ stable main
    state: present
    filename: kubernetes

- name: Обновить apt после добавления репозитория Kubernetes
  apt:
    update_cache: yes

- name: Установить Docker
  apt:
    name:
      - docker-ce={{ docker_version }}
      - docker-ce-cli={{ docker_version }}
      - containerd.io
    state: present
    update_cache: yes

- name: Установить kubeadm, kubelet и kubectl
  apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
    update_cache: yes

- name: Зафиксировать версию Kubernetes пакетов
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - kubelet
    - kubeadm
    - kubectl
    - docker-ce
    - docker-ce-cli